const phrases = [
  {
    id: 0,
    phrase: 'Something ___ happened here.',
    correctAnswer: 'strange',
    incorrectAnswer: 'green',
    difficulty: 0,
  },
  {
    id: 1,
    phrase: 'I just ___ a brand new car.',
    correctAnswer: 'bought',
    incorrectAnswer: 'buy',
    difficulty: 0,
  },
  {
    id: 2,
    phrase: 'Lisa forgot to take her brand new ___ from home.',
    correctAnswer: 'purse',
    incorrectAnswer: 'shoe',
    difficulty: 0,
  },
  {
    id: 3,
    phrase: 'Harry has a really ___ motorbike.',
    correctAnswer: 'fast',
    incorrectAnswer: 'big',
    difficulty: 0,
  },
  {
    id: 4,
    phrase: 'I ___ some shopping today.',
    correctAnswer: 'did',
    incorrectAnswer: 'done',
    difficulty: 0,
  },
  {
    id: 5,
    phrase: 'Maya got us some ___ apples.',
    correctAnswer: 'red',
    incorrectAnswer: 'purple',
    difficulty: 0,
  },
  {
    id: 6,
    phrase: 'I forgot my ___ from school.',
    correctAnswer: 'pencil case',
    incorrectAnswer: 'missing',
    difficulty: 0,
  },
  {
    id: 7,
    phrase: "I'm tired. I ___ too much.",
    correctAnswer: 'work',
    incorrectAnswer: 'sleep',
    difficulty: 0,
  },
  {
    id: 8,
    phrase: 'John ___ that he works out a lot.',
    correctAnswer: 'said',
    incorrectAnswer: 'say',
    difficulty: 0,
  },
  {
    id: 9,
    phrase: 'She ___ forgets to do her homework.',
    correctAnswer: 'often',
    incorrectAnswer: 'frequent',
    difficulty: 0,
  },
  {
    id: 10,
    phrase: '___ is too shy to approach us.',
    correctAnswer: 'He',
    incorrectAnswer: 'We',
    difficulty: 0,
  },
  {
    id: 11,
    phrase: 'They love watching ___ movies.',
    correctAnswer: 'comedy',
    incorrectAnswer: 'keyboard',
    difficulty: 0,
  },
  {
    id: 12,
    phrase: "Zoe's favourite animal has to be a ___.",
    correctAnswer: 'giraffe',
    incorrectAnswer: 'iron',
    difficulty: 0,
  },
  {
    id: 13,
    phrase: 'Her least ___ vegetable is broccoli.',
    correctAnswer: 'favorite',
    incorrectAnswer: 'liking',
    difficulty: 0,
  },
  {
    id: 14,
    phrase: "We'll have to do it again ___.",
    correctAnswer: 'sometime',
    incorrectAnswer: 'yesterday',
    difficulty: 0,
  },
  {
    id: 15,
    phrase: '___ is known as the king of the jungle.',
    correctAnswer: 'Lion',
    incorrectAnswer: 'Monkey',
    difficulty: 0,
  },
  {
    id: 16,
    phrase: 'Daisy, you look ___ today.',
    correctAnswer: 'beautiful',
    incorrectAnswer: 'yellow',
    difficulty: 0,
  },
  {
    id: 17,
    phrase: 'I never ___ I would go skydiving.',
    correctAnswer: 'thought',
    incorrectAnswer: 'thinked',
    difficulty: 0,
  },
  {
    id: 18,
    phrase: 'I love ___ gummies.',
    correctAnswer: 'eating',
    incorrectAnswer: 'gliding',
    difficulty: 0,
  },
  {
    id: 19,
    phrase: 'Ania said she would ___ me how to rollerblade.',
    correctAnswer: 'teach',
    incorrectAnswer: 'missing',
    difficulty: 0,
  },
  {
    id: 20,
    phrase: 'Hey, what ___ is it now?',
    correctAnswer: 'time',
    incorrectAnswer: 'clock',
    difficulty: 0,
  },
  {
    id: 21,
    phrase: 'Which button ___ the game?',
    correctAnswer: 'activates',
    incorrectAnswer: 'missing',
    difficulty: 0,
  },
  {
    id: 22,
    phrase: 'The ___ is the heaviest animal in the world.',
    correctAnswer: 'whale',
    incorrectAnswer: 'dolphin',
    difficulty: 0,
  },
  {
    id: 23,
    phrase: "Daria's phone broke ___.",
    correctAnswer: 'recently',
    incorrectAnswer: 'tomorrow',
    difficulty: 0,
  },
  {
    id: 24,
    phrase: 'Practise ___ perfect.',
    correctAnswer: 'makes',
    incorrectAnswer: 'runs',
    difficulty: 0,
  },
  {
    id: 25,
    phrase: 'Better ___ than never.',
    correctAnswer: 'late',
    incorrectAnswer: 'now',
    difficulty: 0,
  },
  {
    id: 26,
    phrase: '___ said than done.',
    correctAnswer: 'Easier',
    incorrectAnswer: 'Harder',
    difficulty: 0,
  },
  {
    id: 27,
    phrase: "Damian's favorite ___ is geography.",
    correctAnswer: 'subject',
    incorrectAnswer: 'animal',
    difficulty: 0,
  },
  {
    id: 28,
    phrase: 'I ___ to skateboard.',
    correctAnswer: 'used',
    incorrectAnswer: 'using',
    difficulty: 0,
  },
  {
    id: 29,
    phrase: 'Henry won the main prize in a photo ___.',
    correctAnswer: 'contest',
    incorrectAnswer: 'camera',
    difficulty: 0,
  },

  {
    id: 30,
    phrase: 'Matthew is only interested ___ making money.',
    correctAnswer: 'in',
    incorrectAnswer: 'with',
    difficulty: 1,
  },
  {
    id: 31,
    phrase: 'Patricia is very good ___ basketball.',
    correctAnswer: 'at',
    incorrectAnswer: 'on',
    difficulty: 1,
  },
  {
    id: 32,
    phrase: 'She sings ___.',
    correctAnswer: 'beautifully',
    incorrectAnswer: 'beautiful',
    difficulty: 1,
  },
  {
    id: 33,
    phrase: 'Did he ___ the message?',
    correctAnswer: 'read',
    incorrectAnswer: 'become',
    difficulty: 1,
  },
  {
    id: 34,
    phrase: 'I ___ Spanish for 2 years now.',
    correctAnswer: 'have been learning',
    incorrectAnswer: 'learn',
    difficulty: 1,
  },
  {
    id: 35,
    phrase: 'My mom is really afraid of ___ by plane.',
    correctAnswer: 'going',
    incorrectAnswer: 'go',
    difficulty: 1,
  },
  {
    id: 36,
    phrase: 'Can we ___ for a minute?',
    correctAnswer: 'talk',
    incorrectAnswer: 'say',
    difficulty: 1,
  },
  {
    id: 37,
    phrase: 'Rome ___ in a day.',
    correctAnswer: 'was not built',
    incorrectAnswer: 'has not been built',
    difficulty: 1,
  },
  {
    id: 38,
    phrase: "Who's the man ___ the picture?",
    correctAnswer: 'in',
    incorrectAnswer: 'on',
    difficulty: 1,
  },
  {
    id: 39,
    phrase: 'I used to ___ early in the morning.',
    correctAnswer: 'get up',
    incorrectAnswer: 'wake on',
    difficulty: 1,
  },
  {
    id: 40,
    phrase: 'You should ask him ___.',
    correctAnswer: 'politely',
    incorrectAnswer: 'rude',
    difficulty: 1,
  },
  {
    id: 41,
    phrase: 'They ___ 3 years in state prison.',
    correctAnswer: 'spent',
    incorrectAnswer: 'have spend',
    difficulty: 1,
  },
  {
    id: 42,
    phrase: 'Can you take a picture of ___?',
    correctAnswer: 'me',
    incorrectAnswer: 'they',
    difficulty: 1,
  },
  {
    id: 43,
    phrase: 'Yesterday, we ___ Jenny and Tom.',
    correctAnswer: 'saw',
    incorrectAnswer: 'see',
    difficulty: 1,
  },
  {
    id: 44,
    phrase: 'There ___ enough soda for all of us.',
    correctAnswer: 'is not',
    incorrectAnswer: 'were not',
    difficulty: 1,
  },
  {
    id: 45,
    phrase: 'Her house ___ in 1950.',
    correctAnswer: 'was built',
    incorrectAnswer: 'has been build',
    difficulty: 1,
  },
  {
    id: 46,
    phrase: 'Danny ___ any pets.',
    correctAnswer: 'does not have',
    incorrectAnswer: 'have got',
    difficulty: 1,
  },
  {
    id: 47,
    phrase: 'Khloe has ___ old motorcycle.',
    correctAnswer: 'an',
    incorrectAnswer: 'a',
    difficulty: 1,
  },
  {
    id: 48,
    phrase: 'I can never resist ___.',
    correctAnswer: 'sugar',
    incorrectAnswer: 'work',
    difficulty: 1,
  },
  {
    id: 49,
    phrase: "We don't have ___ money.",
    correctAnswer: 'much',
    incorrectAnswer: 'many',
    difficulty: 1,
  },
  {
    id: 50,
    phrase: 'The weather ___ is worse than yesterday.',
    correctAnswer: 'outside',
    incorrectAnswer: 'inside',
    difficulty: 1,
  },
  {
    id: 51,
    phrase: 'Would you like ___ apple?',
    correctAnswer: 'an',
    incorrectAnswer: 'the',
    difficulty: 1,
  },
  {
    id: 52,
    phrase: 'We ___ water sports.',
    correctAnswer: 'love',
    incorrectAnswer: 'like not',
    difficulty: 1,
  },
  {
    id: 53,
    phrase: 'Claudia has not been on holiday ___ 2019.',
    correctAnswer: 'since',
    incorrectAnswer: 'from',
    difficulty: 1,
  },
  {
    id: 54,
    phrase: "Let's play again ___ week.",
    correctAnswer: 'next',
    incorrectAnswer: 'previous',
    difficulty: 1,
  },
  {
    id: 55,
    phrase: 'Andrew, ___ is a good friend of mine, sent me an invitation to his birthday.',
    correctAnswer: 'who',
    incorrectAnswer: 'he',
    difficulty: 1,
  },
  {
    id: 56,
    phrase: "I was looking for my phone, but I couldn't find it ___.",
    correctAnswer: 'anywhere',
    incorrectAnswer: 'somewhere',
    difficulty: 1,
  },
  {
    id: 57,
    phrase: 'Danielle just passed her last ___.',
    correctAnswer: 'exam',
    incorrectAnswer: 'meal',
    difficulty: 1,
  },
  {
    id: 58,
    phrase: 'Why ___ Tommy join us?',
    correctAnswer: "won't",
    incorrectAnswer: "isn't",
    difficulty: 1,
  },
  {
    id: 59,
    phrase: "Natalia's mom is ___ a sweet person.",
    correctAnswer: 'such',
    incorrectAnswer: 'very',
    difficulty: 1,
  },

  {
    id: 60,
    phrase: 'He said he ___ feeling well.',
    correctAnswer: "wasn't",
    incorrectAnswer: "didn't",
    difficulty: 2,
  },
  {
    id: 61,
    phrase: "If you ___ tell me, I'll be angry.",
    correctAnswer: "don't",
    incorrectAnswer: "didn't",
    difficulty: 2,
  },
  {
    id: 62,
    phrase: 'He goes there every ___.',
    correctAnswer: 'day',
    incorrectAnswer: 'days',
    difficulty: 2,
  },
  {
    id: 63,
    phrase: 'I get up late at Saturdays, ___ during winter.',
    correctAnswer: 'particularly',
    incorrectAnswer: 'including',
    difficulty: 2,
  },
  {
    id: 64,
    phrase: '___ your cigarette before entering the building.',
    correctAnswer: 'Put out',
    incorrectAnswer: 'Distinguish',
    difficulty: 2,
  },
  {
    id: 65,
    phrase: 'Marlene keeps ___ in good condition by playing sports.',
    correctAnswer: 'herself',
    incorrectAnswer: 'themselves',
    difficulty: 2,
  },
  {
    id: 66,
    phrase: "I heard he's a ___ football player.",
    correctAnswer: 'promising',
    incorrectAnswer: 'hoping',
    difficulty: 2,
  },
  {
    id: 67,
    phrase: 'They stared at him in complete ___.',
    correctAnswer: 'silence',
    incorrectAnswer: 'silent',
    difficulty: 2,
  },
  {
    id: 68,
    phrase: 'The ___ of the old house made us slightly afraid.',
    correctAnswer: 'quietness',
    incorrectAnswer: 'quiety',
    difficulty: 2,
  },
  {
    id: 69,
    phrase: 'We had to make some changes in order to improve ___.',
    correctAnswer: 'efficiency',
    incorrectAnswer: 'effectiv',
    difficulty: 2,
  },
  {
    id: 70,
    phrase: '___ makes you wise.',
    correctAnswer: 'Reading',
    incorrectAnswer: 'Smoking',
    difficulty: 2,
  },
  {
    id: 71,
    phrase: 'Do not ride the ___ in case of fire!',
    correctAnswer: 'elevator',
    incorrectAnswer: 'bike',
    difficulty: 2,
  },
  {
    id: 72,
    phrase: 'Ashley studies only by ___.',
    correctAnswer: 'herself',
    incorrectAnswer: 'himself',
    difficulty: 2,
  },
  {
    id: 73,
    phrase: 'Could you ___ help me?',
    correctAnswer: 'please',
    incorrectAnswer: 'now',
    difficulty: 2,
  },
  {
    id: 74,
    phrase: 'My parents ___ permission to stay outside a little longer.',
    correctAnswer: 'gave me',
    incorrectAnswer: 'give the',
    difficulty: 2,
  },
  {
    id: 75,
    phrase: 'Time ___ if the decision was right.',
    correctAnswer: 'will tell',
    incorrectAnswer: "won't say",
    difficulty: 2,
  },
  {
    id: 76,
    phrase: 'Jim ___ his grandmother every weekend.',
    correctAnswer: 'visits',
    incorrectAnswer: 'visit',
    difficulty: 2,
  },
  {
    id: 77,
    phrase: 'He takes care of an ___ cat.',
    correctAnswer: 'abandoned',
    incorrectAnswer: 'left',
    difficulty: 2,
  },
  {
    id: 78,
    phrase: 'I ___ that if I were you.',
    correctAnswer: "wouldn't do",
    incorrectAnswer: 'will make',
    difficulty: 2,
  },
  {
    id: 79,
    phrase: "They're always talking to ___ other.",
    correctAnswer: 'each',
    incorrectAnswer: 'one',
    difficulty: 2,
  },
  {
    id: 80,
    phrase: 'Wow, these ___ are really accurate.',
    correctAnswer: 'calculations',
    incorrectAnswer: 'sketches',
    difficulty: 2,
  },
  {
    id: 81,
    phrase: 'Patricia really likes chocolate. You ___ she has a sweet tooth.',
    correctAnswer: 'could say',
    incorrectAnswer: 'can talk',
    difficulty: 2,
  },
  {
    id: 82,
    phrase: 'Dad needs to take ___.',
    correctAnswer: 'a rest',
    incorrectAnswer: 'a part',
    difficulty: 2,
  },
  {
    id: 83,
    phrase: "Everyone's just looking for ___.",
    correctAnswer: 'happiness',
    incorrectAnswer: 'boredom',
    difficulty: 2,
  },
  {
    id: 84,
    phrase: '___ is key.',
    correctAnswer: 'Patience',
    incorrectAnswer: 'Patient',
    difficulty: 2,
  },
  {
    id: 85,
    phrase: 'This test gives an indication of ___.',
    correctAnswer: 'intelligence',
    incorrectAnswer: 'intelligent',
    difficulty: 2,
  },
  {
    id: 86,
    phrase: '___ has risen since last quarter.',
    correctAnswer: 'Unemployment',
    incorrectAnswer: 'Inemployment',
    difficulty: 2,
  },
  {
    id: 87,
    phrase: 'Marie ___ raw carrots.',
    correctAnswer: 'always eats',
    incorrectAnswer: 'eat often',
    difficulty: 2,
  },
  {
    id: 88,
    phrase: 'How many ___ do you have?',
    correctAnswer: 'siblings',
    incorrectAnswer: 'people',
    difficulty: 2,
  },
  {
    id: 89,
    phrase: 'Do you have this shirt ___?',
    correctAnswer: 'in blue',
    incorrectAnswer: 'with blue',
    difficulty: 2,
  },
];

export default phrases;
